# Generated by Django 4.2.30 on 2026-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_faq_message_voice_note_report_is_escalated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGuideConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main_guide', max_length=50, unique=True)),
                ('english_text', models.TextField()),
                ('luo_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated to Agency'), ('SANCTION_PENDING', 'Agency Sanction Pending'), ('LEGAL_REFERRAL', 'Legal Referral / Judiciary'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING_REVIEW', max_length=20),
        ),
    ]
