# Generated by Django 6.0.4 on 2026-05-17 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auditlog_ip_address_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioguideconfig',
            name='english_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_guides/'),
        ),
        migrations.AddField(
            model_name='audioguideconfig',
            name='english_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioguideconfig',
            name='english_source',
            field=models.CharField(choices=[('text_to_speech', 'System Text-to-Speech'), ('uploaded_file', 'Uploaded Audio File'), ('url', 'External Audio URL')], default='text_to_speech', max_length=20),
        ),
        migrations.AddField(
            model_name='audioguideconfig',
            name='luo_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_guides/'),
        ),
        migrations.AddField(
            model_name='audioguideconfig',
            name='luo_audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioguideconfig',
            name='luo_source',
            field=models.CharField(choices=[('text_to_speech', 'System Text-to-Speech'), ('uploaded_file', 'Uploaded Audio File'), ('url', 'External Audio URL')], default='text_to_speech', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mp3', 'wav', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='report',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='reportevidence',
            name='file',
            field=models.FileField(upload_to='evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mp3', 'wav'])]),
        ),
    ]
